name: build

on:
  push:
    branches:
      - master

jobs:
  uptime:
    name: updown-webhook
    runs-on: ubuntu-latest
    env:
      REPO: dazwilkin/updown-webhook
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: get-version
        run: echo "VERSION=$(uname --kernel-release)" >> ${GITHUB_ENV}
      - name: webhook
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            TOKEN=${{ secrets.GHCR }}
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          push: true
